/*
 * This source file was generated by the Gradle 'init' task
 */

#ifndef RUBYENGINE_H
#define RUBYENGINE_H

#ifdef _WIN32
#define RUBYENGINE_EXPORT_FUNC __declspec(dllexport)
#else
#define RUBYENGINE_EXPORT_FUNC
#endif

#include <string>
#include <flecs.h>
#include <glm/glm.hpp>

#include <Window.h>
#include <shaders/Shader.h>
#include "nodes/3d/Node3d.h"
#include "components/3d/Components3d.h"
#include "resources/Material.h"
#include "resources/Mesh.h"
#include <util/MeshVao.h>

namespace RubyEngine {
class Greeter {
public:
    std::string RUBYENGINE_EXPORT_FUNC greeting();
};

} // namespace RubyEngine

class Ruby {
public:
    static flecs::world world;
    static flecs::query<Transform3d, MeshVao, Material> renderables;
    static glm::mat4 computeWorldTransform(flecs::entity e);

    void start();
};

#endif
