/*
 * This source file was generated by the Gradle 'init' task
 */

#ifndef RUBYENGINE_H
#define RUBYENGINE_H

#ifdef _WIN32
#define RUBYENGINE_EXPORT_FUNC __declspec(dllexport)
#else
#define RUBYENGINE_EXPORT_FUNC
#endif

#include <string>

namespace RubyEngine {
    class Greeter {
        public:
        std::string RUBYENGINE_EXPORT_FUNC greeting();
    };
}

#endif
