/*
 * This source file was generated by the Gradle 'init' task
 */

#ifndef VELV_H
#define VELV_H

#ifdef _WIN32
#define VELV_EXPORT_FUNC __declspec(dllexport)
#else
#define VELV_EXPORT_FUNC
#endif

#include <string>

namespace velv {
    class Greeter {
        public:
        std::string VELV_EXPORT_FUNC greeting();
    };
}

#endif
