/*
 * This source file was generated by the Gradle 'init' task
 */

#include <cassert>
#include <RubyEngine.h>

int main() {
    RubyEngine::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
