/*
 * This source file was generated by the Gradle 'init' task
 */

#include <iostream>
#include <stdlib.h>
#include <src/ruby/engine/headers/app.h>

int main () {
    RubyEngine::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    return 0;
}
