/*
 * This source file was generated by the Gradle 'init' task
 */

#include <iostream>
#include <stdlib.h>
#include "velv.h"

std::string velv::Greeter::greeting() {
    return std::string("Hello, World!");
}
