/*
 * This source file was generated by the Gradle 'init' task
 */

#include <iostream>
#include <stdlib.h>
#include <src/ruby/engine/headers/app.h>

// std::string RubyEngine::Greeter::greeting() {
//     return std::string("Hello, World!");
// }

int main () {
    RubyEngine::Greeter greeter;
    std::cout << greeter.greeting() << "!!!!!!!!" << std::endl;
    return 0;
}
