/*
 * This source file was generated by the Gradle 'init' task
 */

#include <iostream>
#include <stdlib.h>
#include <RubyEngine.h>

int main () {
    RubyEngine::Greeter greeter;
    std::cout << greeter.greeting() << "Proto!" << std::endl;
    return 0;
}
